### ISSUE TITLE
Possible bug after running for a period of time

### ISSUE THREAD

**Issue by ashmckenzie** [happy-bubbles/presence#12]
Am running the presence app under Docker and behind traefik and it appears after ~24 hours (or somewhere around that mark) the UI can no longer connect to the wss endpoint (according to Firefox's console).

I'll endeavour to rule in/out traefik as the problem here..

**Comment by nemik** [comment]
I would check traefik then and maybe docker? I have the presence server running for months on my home server but it's accessed from behind nginx with `proxy_pass` (a reverse proxy) and it works fine. I also just run it as the executable and not behind docker.

**Comment by ashmckenzie** [comment]
Thanks, it's looking more like when MQTT goes down (or is upgraded), sorry I haven't got specifics at this stage :(

**Comment by nemik** [comment]
No worries, I hope you track it down. If it is something on the presence server please file a bug and I'll have a look at it :)

**Comment by ashmckenzie** [comment]
Closing until I have something actionable :)
