### ISSUE TITLE
Json handling query 

### ISSUE THREAD

**Issue by vaibhavkambli** [happy-bubbles/presence#13]
Can u please put some light on following code, i am trying to understand few things in presence server.
I tried to understand how your handling incoming json data on mqtt, how its getting stored.
Following function returns chan<- Incoming_json. what that exactly does ?
**func IncomingMQTTProcessor(updateInterval time.Duration, cl *client.Client, db *bolt.DB) chan<- Incoming_json {}** 
Also it has case **case incoming := <-incoming_msgs_chan:**
while following functionality 
**incoming = incomingBeaconFilter(incoming)
this_beacon_id := getBeaconID(incoming)**

can u please explain how ur using channel for incoming json ? and incoming object .

**Comment by nemik** [comment]
The code will subscribe to an MQTT topic and each message comes in and gets sent to that incoming channel which has a queue, that message processor function makes sure to run for each message but only one at a time otherwise there would be race conditions. So the purpose of the channel is to make sure that each message gets processed and in the order they come in over MQTT.

**Comment by vaibhavkambli** [comment]
Hello **Nemik**,
 thanks for your reply.
I am able to understand the logic behind your code, but have few confusions in methods as i am not expert in go, i just started for this project only.
Please find mentioned points below.
1. function  IncomingMQTTProcessor returns incoming_msgs_chan (channel of type Incoming_json)
	`incoming_msgs_chan := make(chan Incoming_json, 10)`

2. While calling function IncomingMQTTProcessor in main ,  your assigning its return value to channel incoming_updates_chan  (channel of same type Incoming_json)
`incoming_updates_chan := IncomingMQTTProcessor(1*time.Second, cli, db)`

3. In MQTT subscriber handler your passing unmarshaled Json data stored in incoming to channel incoming_updates_chan 
``` 
//pass this to the state monitor
incoming_updates_chan <- incoming 
```
So incoming data is getting stored in `incoming_updates_chan  `as soon as its get received from MQTT response,  in parallel world IncomingMQTTProcessor get called for first time and initialize buffered channel of size 10, i.e `incoming_msgs_chan`  and start go routine which contain select and cases and check for data available on `incoming_msgs_chan `, if he found data it process by taking into `incoming` and at the end of routine returns `incoming_msgs_chan `
```
go func() {
   for {
     select {
        case incoming := <-incoming_msgs_chan:
```
**End**
```
}()
	return incoming_msgs_chan
```
My only confusion is your stored data in `incoming_updates_chan  `from `incoming `and checking `incoming_msgs_chan` in go routine, is that mean both channel are same ?
Also What is need of incoming_msgs_chan should be of size more than 1 (10 in code ) as we are receiving only one at a time and processing ?
