### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by mph88** [happy-bubbles/presence#15]
Setup a fresh FreeBSD jail for happybubbles and installed the go package. I can issue the presence command to start the server, see that I'm connected to MQTT, the Happy Bubbles text, and "Visit http://localhost:5555 on your browser to see the web interface". Upon going to that page I get a page with the text "404 page not found"

**Comment by nemik** [comment]
That's strange. I haven't tested any of this in a BSD system. Can you check to see that it's actually the presence server bound and listening on port 5555?

**Comment by mph88** [comment]
I figured out the issue. I moved the static_html directory to where I run the binary and everything worked just fine! For Freebsd the presence binary was located in root/go/bin.
