### ISSUE TITLE
1.8.2 no device tracking

### ISSUE THREAD

**Issue by rockinglama** [happy-bubbles/presence#18]
After I updated from 1.8.1 to 1.8.2 the device tracking does not work anymore.
Previously added beacons don't show up anymore.
Correct mqtt messages from happybubbles are coming in just fine.

Did a clean install with new db, added my beacons on the "latest beacon seen" page.
Same problem, devices do not show up in the added beacons section on the home page
and are note reported to my home-assistant instance via mqtt.

**Comment by rockinglama** [comment]
my fault:
since the new version has a default minimum rssi of 90
and it seems like all my beacons were above that limit

would be less confusing though, if devices were shown in the added beacon section, even if not in range

**Comment by nemik** [comment]
Oh thanks for telling me about this. Your suggestion for beacons still showing up is important and I should include that. Thanks!

**Comment by frenck** [comment]
This is a great feature!
The field should be empty / not set though, in order to prevent surprises with existing users.
