### ISSUE TITLE
Domoticz MQTT support

### ISSUE THREAD

**Issue by brian-f** [happy-bubbles/presence#6]
Do you have any plan to support Domoticz via MQTT? https://www.domoticz.com/wiki/MQTT

Seems like it's just a matter of adding an IDX value of a virtual switch to the payload and On/Off nvalue based on presence.
TIA

**Comment by nemik** [comment]
Sorry I don't use Domoticz, and don't have time at the moment to add support. It is an open source project though and I've tried hard to document it, so contributions from the Domoticz community are welcome.
